apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: backend-config
    behavior: replace
    envs:
      - configmap.env

namespace: default
